---
- name: Create the hidra_exporter group
  group:
    name: "{{ _hidra_exporter_system_group }}"
    state: present
    system: true
  when: _hidra_exporter_system_group != "root"

- name: Create the hidra_exporter user
  user:
    name: "{{ _hidra_exporter_system_user }}"
    groups: "{{ _hidra_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: _hidra_exporter_system_user != "root"

- block:
    - name: Download hidra_exporter binary to local folder
      become: false
      get_url:
        url: https://github.com/hidracloud/hidra/releases/download/v{{ hidra_exporter_version }}/hidra_{{ hidra_exporter_version }}_linux_{{ go_arch }}.tar.gz
        dest: "/tmp/hidra_{{ hidra_exporter_version }}_linux_{{ go_arch }}.tar.gz"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack hidra binary
      become: false
      unarchive:
        src: "/tmp/hidra_{{ hidra_exporter_version }}_linux_{{ go_arch }}.tar.gz"
        dest: "/tmp"
        mode: '0755'
      delegate_to: localhost
      check_mode: false

    - name: Propagate hidra_exporter binaries
      copy:
        src: "/tmp/hidra"
        dest: "{{ _hidra_exporter_binary_install_dir }}/hidra"
        mode: 0755
        owner: root
        group: root
      notify: restart hidra_exporter
      when: not ansible_check_mode
  when: hidra_exporter_binary_local_dir | length == 0

- name: propagate locally distributed hidra_exporter binary
  copy:
    src: "{{ hidra_exporter_binary_local_dir }}/hidra"
    dest: "{{ _hidra_exporter_binary_install_dir }}/hidra"
    mode: 0755
    owner: root
    group: root
  when: hidra_exporter_binary_local_dir | length > 0
  notify: restart hidra_exporter

- name: install dependencies
  package:
    name: 
      - chromium-driver
      - rsync
    state: latest
    